# Generated by Django 3.1.3 on 2021-04-12 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Audiance_language', models.CharField(choices=[('english', 'English'), ('russian', 'Russian'), ('turkish', 'Turkish')], default='27', max_length=25)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Audiance_location', models.CharField(choices=[('afghanistan', 'Afghanistan'), ('albania', 'Albania'), ('algeria', 'Algeria')], default='113', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuerySetRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('lastchanged', models.DateTimeField(auto_now=True)),
                ('lead_ownership', models.CharField(choices=[('project', 'Project'), ('company', 'Company'), ('allLead', 'All Lead')], default='allLeads', max_length=120)),
                ('attribute', models.CharField(choices=[('age_range', 'age range'), ('interests', 'interests'), ('location', 'location'), ('language', 'language')], default='interests', max_length=120)),
                ('interaction', models.CharField(choices=[('last_purchase_date', 'last purchase date'), ('last_product_purchased', 'last product purchased'), ('last_page_visit', 'last page visit'), ('last_email_open', 'last email open'), ('last_touchpoint_date', 'last touchpoint date'), ('last_newsletter_signup', 'last newsletter signup'), ('purchased_product_combination', 'purchased product combination'), ('specific_product_last_purchase_date', 'specific product last purchase date')], default='last_purchase_date', max_length=120)),
                ('method_type', models.CharField(choices=[('filter', 'Include'), ('exclude', 'Exclude')], default='filter', max_length=12)),
                ('field_name', models.CharField(max_length=128, verbose_name='Field name of Selector')),
                ('lookup_type', models.CharField(choices=[('exact', 'exactly'), ('iexact', 'exactly (case insensitive)'), ('contains', 'contains'), ('icontains', 'contains (case insensitive)'), ('regex', 'regex'), ('iregex', 'contains (case insensitive)'), ('gt', 'greater than'), ('gte', 'greater than or equal to'), ('lt', 'less than'), ('lte', 'less than or equal to'), ('startswith', 'starts with'), ('endswith', 'starts with'), ('istartswith', 'ends with (case insensitive)'), ('iendswith', 'ends with (case insensitive)')], default='exact', max_length=12)),
                ('field_value', models.CharField(help_text='Can be anything from a number, to a string. Or, do `now-7 days` or `today+3 days` for fancy timedelta.', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SelectionProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=80)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Selector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=80)),
                ('include_or_exclude', models.CharField(max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
