# Generated by Django 3.1.3 on 2021-04-12 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaign', '0001_initial'),
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='selector',
            name='age_ranges',
            field=models.ManyToManyField(to='crm.AudienceAgeRange'),
        ),
    ]
