# Generated by Django 3.1.3 on 2021-04-14 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0004_auto_20210413_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thirdchoice',
            name='age_ranges',
        ),
        migrations.RemoveField(
            model_name='thirdchoice',
            name='interest',
        ),
        migrations.RemoveField(
            model_name='thirdchoice',
            name='languages',
        ),
        migrations.RemoveField(
            model_name='thirdchoice',
            name='locations',
        ),
        migrations.AddField(
            model_name='thirdchoice',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
