# Generated by Django 3.1.3 on 2021-04-15 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0006_auto_20210414_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thirdchoice',
            name='name',
            field=models.CharField(max_length=130),
        ),
    ]
