# Generated by Django 3.1.3 on 2021-04-12 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('filemanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filemanager_company_document', to='users.company'),
        ),
        migrations.AddField(
            model_name='document',
            name='organizations',
            field=models.ManyToManyField(to='users.Organization'),
        ),
    ]
